-- | 代数系の型クラス階層を Graphviz dot および HTML で出力する (静的).
module G2Zoo.AlgebraHier
  ( renderAlgebraHierDot
  , renderAlgebraHierHtml
  ) where

-- | 代数系の型クラス階層を dot 形式で返す.
--
-- 含まれる構造:
-- * 代数系列: Magma → Semigroup → Monoid → Group
-- * 順序列:   Preorder → PartialOrder → (LinearOrder / BoundedLattice → ... → APS)
-- * APS 列:   BoundedLattice → PreAPS → APS → {FixedPointAPS, ImpAPS, LoebAPS}
renderAlgebraHierDot :: String
renderAlgebraHierDot = unlines
  [ "// Algebra Hierarchy -- auto-generated by g2-zoo"
  , "digraph AlgebraHier {"
  , "  rankdir=TB;"
  , "  bgcolor=\"white\";"
  , "  graph [nodesep=1.1, ranksep=0.9, splines=spline, overlap=false];"
  , "  node  [shape=plaintext, fontsize=13];"
  , "  edge  [arrowsize=0.7, penwidth=1.0];"
  , ""
  , "  // 代数系 (左列)"
  , "  Magma     [label=\"Magma\"];"
  , "  Semigroup [label=\"Semigroup\"];"
  , "  Monoid    [label=\"Monoid\"];"
  , "  Group     [label=\"Group\"];"
  , "  Magma -> Semigroup -> Monoid -> Group;"
  , ""
  , "  // 順序系 (中左列)"
  , "  Preorder [label=\"Preorder\"];"
  , "  PartOrd  [label=\"PartialOrder\"];"
  , "  LinOrd   [label=\"LinearOrder\"];"
  , "  Preorder -> PartOrd;"
  , "  PartOrd  -> LinOrd;"
  , ""
  , "  // 束・領域系 (中右列)"
  , "  BdLat  [label=\"BoundedLattice\"];"
  , "  CpLat  [label=\"CompleteLattice\"];"
  , "  AlgDom [label=\"AlgebraicDomain\"];"
  , "  PartOrd -> BdLat -> CpLat -> AlgDom;"
  , ""
  , "  // APS 系 (右列)"
  , "  PreAPS  [label=\"PreAPS\"];"
  , "  APS     [label=\"APS\"];"
  , "  FpAPS   [label=\"FixedPointAPS\"];"
  , "  ImpAPS  [label=\"ImpAPS\"];"
  , "  LoebAPS [label=\"LoebAPS\"];"
  , "  BdLat  -> PreAPS -> APS;"
  , "  APS    -> FpAPS;"
  , "  APS    -> ImpAPS   [constraint=false];"
  , "  APS    -> LoebAPS  [constraint=false];"
  , ""
  , "  // ランク揃え"
  , "  { rank=same; Magma; Preorder }"
  , "  { rank=same; Semigroup; PartOrd }"
  , "  { rank=same; Monoid; LinOrd; BdLat; PreAPS }"
  , "  { rank=same; Group; CpLat; APS }"
  , "  { rank=same; AlgDom; FpAPS; ImpAPS; LoebAPS }"
  , "}"
  ]

-- | 代数系階層の HTML ページを生成する.
-- zoo-algebra.png が同ディレクトリにあることを前提とする.
renderAlgebraHierHtml :: String
renderAlgebraHierHtml = unlines
  [ "<!DOCTYPE html>"
  , "<html lang=\"ja\"><head>"
  , "<meta charset=\"UTF-8\">"
  , "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
  , "<title>G2-Zoo: 代数系階層図</title>"
  , "<style>" ++ pageCss ++ "</style>"
  , "</head><body>"
  , "<h1>代数系の階層図</h1>"
  , "<p>APS (Abstract Provability Structure) の位置づけを代数系全体の中で示す。"
  , "矢印 A &rarr; B は「B は A の特殊化 (B は A の要件を満たす)」を意味する。</p>"
  , "<img src=\"zoo-algebra.png\" alt=\"代数系階層図\">"
  , "<h2>各構造の説明</h2>"
  , "<table>"
  , "<thead><tr><th>名称</th><th>要件</th><th>備考</th></tr></thead>"
  , "<tbody>"
  , tr "Magma"          "集合 + 二項演算"                    "最も基本的な代数系"
  , tr "Semigroup"      "Magma + 結合則"                    "半群"
  , tr "Monoid"         "Semigroup + 単位元"                "モノイド"
  , tr "Group"          "Monoid + 逆元"                     "群"
  , tr "Preorder"       "反射的かつ推移的な二項関係"          "前順序"
  , tr "PartialOrder"   "Preorder + 反対称性"                "半順序 (偏順序)"
  , tr "LinearOrder"    "PartialOrder + 全順序性"            "線形順序 (全順序)"
  , tr "BoundedLattice" "PartialOrder + 有界な束構造"         "⊤, ⊥, ∧, ∨ を持つ"
  , tr "CompleteLattice" "BoundedLattice + 任意の上限/下限"  "完全束"
  , tr "AlgebraicDomain" "CompleteLattice + コンパクト元十分" "代数的 dcpo"
  , tr "PreAPS"         "BoundedLattice + □ + ☒ 演算"       "公理なし版 APS"
  , tr "APS"            "PreAPS + A1–A4"                    "Abstract Provability Structure"
  , tr "FixedPointAPS"  "APS + ∃x. ☒x = x"                 "☒-不動点を持つ APS"
  , tr "ImpAPS"         "APS + 含意演算 →"                  "内在化条件付き"
  , tr "LoebAPS"        "APS + Loeb 規則"                   "□x≤x⇒⊤≤x"
  , "</tbody></table>"
  , "</body></html>"
  ]
  where
    tr name req note =
      "<tr><td>" ++ name ++ "</td><td>" ++ req ++ "</td><td>" ++ note ++ "</td></tr>"

pageCss :: String
pageCss = concat
  [ "body { background:#fff; color:#000; font-family:monospace; line-height:1.5;"
  , "       margin:0 auto; max-width:900px; padding:1em 2em 3em; }"
  , "h1 { font-size:1.3em; margin:0.3em 0 0.5em; }"
  , "h2 { font-size:1.1em; margin-top:1.2em; border-bottom:1px solid #000; padding-bottom:0.1em; }"
  , "p  { margin:0.3em 0 0.7em; }"
  , "img { display:block; max-width:100%; height:auto; border:1px solid #ccc; margin:0.5em 0 1em; }"
  , "table { border-collapse:collapse; width:100%; }"
  , "th,td { border:1px solid #ccc; padding:3px 8px; text-align:left; font-size:0.9em; }"
  , "th { background:#f5f5f5; }"
  ]
