-- | G2 と FG2 の間の階層専用の dot / HTML 出力.
module G2Zoo.G2Chain
  ( renderG2ChainDot
  , renderG2ChainHtml
  ) where

-- | G2-FG2 階層の dot 文字列を返す (静的).
--
-- 3 段の格子:
--   Level 0 (最強): ∃☒-FP ↔ FG2 (APS 上同値)
--   Level 1 (中間): WFG2
--   Level 2 (最弱): G2   Loeb (ImpAPS)
--
-- 実線 = 成立した含意, 点線赤 = 反例あり, 点線橙 = 未解決.
renderG2ChainDot :: String
renderG2ChainDot = unlines
  [ "// G2-FG2 Hierarchy -- auto-generated by g2-zoo"
  , "digraph G2Chain {"
  , "  rankdir=TB;"
  , "  bgcolor=\"white\";"
  , "  graph [nodesep=1.4, ranksep=0.95, splines=spline, overlap=false];"
  , "  node  [shape=plaintext, fontsize=15];"
  , "  edge  [fontsize=10, penwidth=1.2, arrowsize=0.8];"
  , ""
  , "  // Level 0"
  , "  DFP  [label=\"Diam-FP\"];"
  , "  FG2  [label=\"FG2\"];"
  , ""
  , "  // Level 1"
  , "  WFG2 [label=\"WFG2\"];"
  , ""
  , "  // Level 2"
  , "  G2   [label=\"G2\"];"
  , "  Loeb [label=\"Loeb\"];"
  , ""
  , "  // --- 成立した含意 (実線) ---"
  , "  DFP  -> FG2  [label=\"APS\"];"
  , "  FG2  -> DFP  [label=\"A1\", constraint=false];"
  , "  FG2  -> WFG2 [label=\"PreAPS\"];"
  , "  WFG2 -> G2   [label=\"A1+A2\"];"
  , "  DFP  -> G2   [label=\"APS\", constraint=false];"
  , ""
  , "  // --- 反例あり (点線赤) ---"
  , "  WFG2 -> FG2 [label=\"x APS\","
  , "    style=dotted, color=\"#b00000\", fontcolor=\"#b00000\", constraint=false];"
  , "  G2 -> FG2   [label=\"x APS\","
  , "    style=dotted, color=\"#b00000\", fontcolor=\"#b00000\", constraint=false];"
  , "  G2 -> DFP   [label=\"x APS\","
  , "    style=dotted, color=\"#b00000\", fontcolor=\"#b00000\", constraint=false];"
  , "  DFP -> FG2  [label=\"x A1+A2+A4\","
  , "    style=dotted, color=\"#b00000\", fontcolor=\"#b00000\", constraint=false];"
  , "  G2 -> Loeb  [label=\"x ImpAPS\","
  , "    style=dotted, color=\"#b00000\", fontcolor=\"#b00000\", constraint=false];"
  , ""
  , "  // --- 未解決 (点線橙) ---"
  , "  Loeb -> G2  [label=\"? ImpAPS\","
  , "    style=dotted, color=\"#aa7700\", fontcolor=\"#aa7700\", constraint=false];"
  , ""
  , "  // ランク揃え"
  , "  { rank=same; DFP; FG2 }"
  , "  { rank=same; WFG2 }"
  , "  { rank=same; G2; Loeb }"
  , "}"
  ]

-- | G2-FG2 階層の HTML ページを生成する.
-- zoo-g2chain.png が同ディレクトリにあることを前提とする.
renderG2ChainHtml :: String
renderG2ChainHtml = unlines
  [ "<!DOCTYPE html>"
  , "<html lang=\"ja\"><head>"
  , "<meta charset=\"UTF-8\">"
  , "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
  , "<title>G2-Zoo: G2-FG2 階層図</title>"
  , "<style>" ++ pageCss ++ "</style>"
  , "</head><body>"
  , "<h1>G2-FG2 の階層図</h1>"
  , "<p>G2 (第二不完全性定理) と FG2 (形式化第二不完全性定理) の間の含意関係を整理する。"
  , "実線 = 成立した含意。点線赤 = 反例が存在する (否定方向)。点線橙 = 未解決。</p>"
  , "<img src=\"zoo-g2chain.png\" alt=\"G2-FG2 階層図\">"
  , "<h2>命題の定義</h2>"
  , "<table>"
  , "<thead><tr><th>命題</th><th>定義</th></tr></thead>"
  , "<tbody>"
  , tr "Diam-FP (∃☒-FP)" "∃x. ☒x = x  (☒-不動点の存在)"
  , tr "FG2"              "☒☒⊤ ≤ ☒⊤  (形式化第二不完全性定理)"
  , tr "WFG2"             "☒⊤ ≤ ⊥ ⇒ ☒☒⊤ ≤ ⊥  (弱形式化 G2)"
  , tr "G2"               "☒⊤ ≤ ⊥ ⇒ ⊤ ≤ ⊥  (第二不完全性定理)"
  , tr "Loeb"             "∀x. □x ≤ x ⇒ ⊤ ≤ x  (Loeb 規則)"
  , "</tbody></table>"
  , "<h2>主要な結果</h2>"
  , "<table>"
  , "<thead><tr><th>内容</th><th>文脈</th><th>出典</th></tr></thead>"
  , "<tbody>"
  , tr3 "∃☒-FP → FG2"      "APS"      "B&S 2016 Thm.2"
  , tr3 "∃☒-FP → G2"       "APS"      "B&S 2016 Thm.1"
  , tr3 "FG2 → ∃☒-FP"      "A1"       "Search 検証済"
  , tr3 "FG2 → WFG2 → G2"  "PreAPS/A1+A2" "推移律"
  , tr3 "WFG2 ⇏ FG2"       "APS"      "L4Id 反例 (4点線形)"
  , tr3 "G2 ⇏ FG2"         "APS"      "Case1 反例 (3点線形)"
  , tr3 "G2 ⇏ ∃☒-FP"       "APS"      "Case2 反例 (3点線形)"
  , tr3 "∃☒-FP ⇏ FG2"      "A1+A2+A4" "Case3 反例 (A3 なし)"
  , tr3 "Loeb → G2"         "ImpAPS"   "未解決"
  , tr3 "G2 ⇏ Loeb"         "ImpAPS"   "反例構成済"
  , "</tbody></table>"
  , "</body></html>"
  ]
  where
    tr  a b   = "<tr><td>" ++ a ++ "</td><td>" ++ b ++ "</td></tr>"
    tr3 a b c = "<tr><td>" ++ a ++ "</td><td>" ++ b ++ "</td><td>" ++ c ++ "</td></tr>"

pageCss :: String
pageCss = concat
  [ "body { background:#fff; color:#000; font-family:monospace; line-height:1.5;"
  , "       margin:0 auto; max-width:900px; padding:1em 2em 3em; }"
  , "h1 { font-size:1.3em; margin:0.3em 0 0.5em; }"
  , "h2 { font-size:1.1em; margin-top:1.2em; border-bottom:1px solid #000; padding-bottom:0.1em; }"
  , "p  { margin:0.3em 0 0.7em; }"
  , "img { display:block; max-width:100%; height:auto; border:1px solid #ccc; margin:0.5em 0 1em; }"
  , "table { border-collapse:collapse; width:100%; margin-bottom:1em; }"
  , "th,td { border:1px solid #ccc; padding:3px 8px; text-align:left; font-size:0.9em; }"
  , "th { background:#f5f5f5; }"
  ]
