-- | G2 周辺の命題間の含意関係 (動物園) と Graphviz dot 形式での出力.
--
-- 各 'Edge' は「ある文脈の下で前提から結論への含意が成立する/しない/未解決」という
-- 情報を持つ. 'renderDot' でこのデータを dot 言語のグラフに変換する.
module G2Zoo.Zoo
  ( -- * 命題ノード
    Prop (..)
  , propLabel
  , propRank
  , propColumn
    -- * 文脈
  , Context (..)
  , contextLabel
    -- * 辺
  , EdgeKind (..)
  , Edge (..)
    -- * 動物園
  , defaultZoo
  , filterProved
    -- * dot 出力
  , renderDot
    -- * TikZ / LaTeX 出力
  , renderTikZ
    -- * 注釈・出典の書き出し
  , renderNotes
  ) where

import Data.List  (intercalate, nub, sort, sortBy)
import Data.Ord   (comparing)

-- | 不完全性現象の動物園に登場する命題.
data Prop
  = PG2          -- ^ 第二不完全性定理 G2.
  | PWFG2        -- ^ 弱形式化第二不完全性定理 WFG2.
  | PFG2         -- ^ 形式化第二不完全性定理 FG2.
  | PHasDiamFP   -- ^ ☒-不動点の存在.
  | PHasBoxFP    -- ^ □-不動点の存在.
  | PLoeb        -- ^ Loeb 規則.
  | PFLoeb       -- ^ 形式化 Loeb (FLoeb).
  | PConsistency -- ^ 無矛盾性.
  deriving (Eq, Ord, Show, Enum, Bounded)

-- | dot ラベル用の表示文字列.
propLabel :: Prop -> String
propLabel PG2          = "G2"
propLabel PWFG2        = "WFG2"
propLabel PFG2         = "FG2"
propLabel PHasDiamFP   = "∃☒-FP"
propLabel PHasBoxFP    = "∃□-FP"
propLabel PLoeb        = "Loeb"
propLabel PFLoeb       = "FLoeb"
propLabel PConsistency = "Con"

-- | DOT 画像用の表示文字列。PNG化でフォント依存の強い記号が化けないようにする。
dotPropLabel :: Prop -> String
dotPropLabel PHasDiamFP   = "Diam-FP"
dotPropLabel PHasBoxFP    = "Box-FP"
dotPropLabel p            = propLabel p

-- | 含意が成立する文脈 (どの代数構造の上での話か).
--
-- 'CCustom' は A1+A2 のように任意の公理の組合せを記述するための逃げ場.
data Context
  = COverPreAPS
  | COverAPS
  | COverFixedPointAPS
  | COverLoebAPS
  | COverImpAPS
  | COverFin
  | CCustom String
  deriving (Eq, Ord, Show)

contextLabel :: Context -> String
contextLabel COverPreAPS        = "PreAPS"
contextLabel COverAPS           = "APS"
contextLabel COverFixedPointAPS = "APS+∃☒-FP"
contextLabel COverLoebAPS       = "LoebAPS"
contextLabel COverImpAPS        = "ImpAPS"
contextLabel COverFin           = "fin"
contextLabel (CCustom s)        = s

-- | 辺の種類.
data EdgeKind
  = Proved     -- ^ 含意が成立する (実線).
  | Open       -- ^ 含意の成否が未解決 (破線).
  | Separated  -- ^ 反例モデルが存在する (赤の点線).
  deriving (Eq, Ord, Show)

-- | 動物園の辺. @from@ から @to@ への含意, 文脈と種類を持つ.
data Edge = Edge
  { edgeFrom :: Prop
  , edgeTo   :: Prop
  , edgeCtx  :: Context
  , edgeKind :: EdgeKind
  , edgeNote :: String  -- ^ 出典など (空文字なら省略).
  } deriving (Eq, Show)

-- | seminar1／seminar2／Syntactical Result に書かれている既知の関係を集約した動物園。
--
-- 各辺の出典・注釈は 'edgeNote' に保持するが、画像には載せず
-- 'renderNotes' 経由で別途 Markdown に書き出す。
defaultZoo :: [Edge]
defaultZoo =
  [ -- B&S 2016 主定理
    Edge PHasDiamFP PFG2 COverAPS Proved "B&S 2016 Thm. 2"
  , Edge PHasDiamFP PG2  COverAPS Proved "B&S 2016 Thm. 1"

    -- Syntactical Result メモの Fact
  , Edge PFG2 PG2   (CCustom "A1+A2") Proved "Syntactical Fact"
  , Edge PFG2 PWFG2 COverPreAPS       Proved "推移律から直ちに成立"
  , Edge PWFG2 PG2  (CCustom "A1+A2") Proved "A2: ⊤≤☒⊥, A1: ☒☒⊤≤☒⊥, WFG2 仮定でチェーン"
  , Edge PWFG2 PFG2 COverAPS          Separated "L4反例: 4点線形,☒⊤=a,☒b=a,☒a=b,☒⊥=⊤"

    -- A1 上での部分的な同値関係（FG2 ⇒ ∃☒-FP, 3点線形では成立、Search で検証）
  , Edge PFG2 PHasDiamFP (CCustom "A1") Proved "3点線形上で Search 検証済"

    -- 逆向きは Case1／Case3 で分離
  , Edge PG2  PFG2        COverAPS Separated "Case1"
  , Edge PG2  PHasDiamFP  COverAPS Separated "Case2"
  , Edge PHasDiamFP PFG2  (CCustom "A1+A2+A4") Separated "Case3"

    -- Löb 関連
  , Edge PLoeb PG2 COverImpAPS Open "未解決"
  , Edge PG2   PLoeb COverImpAPS Separated "反例構成済（seminar2）"
  ]

-- | 動物園を Graphviz dot 形式のテキストにレンダリングする。
--
-- 出力は @digraph G { ... }@ 形式。配色は白／青／緑／赤の4色基調で、
-- 文脈ラベル（APS、A1+A2 など）のみ表示し、出典は別ファイルに書き出す。
-- フォントは GitHub Actions 側で入れる Noto Sans CJK JP を指定する。
renderDot :: [Edge] -> String
renderDot es = unlines $
  [ "// G2 Zoo  -- auto-generated by g2-zoo"
  , "digraph G2Zoo {"
  , "  rankdir=TB;"
  , "  bgcolor=\"white\";"
  , "  graph [fontname=\"Noto Sans CJK JP\", nodesep=1.0, ranksep=1.05,"
  , "         concentrate=false, splines=ortho, overlap=false,"
  , "         outputorder=edgesfirst];"
  , "  node  [shape=box, style=\"rounded,filled\", fillcolor=\"white\","
  , "         color=\"#000080\", penwidth=1.2, margin=\"0.14,0.08\","
  , "         fontcolor=\"black\", fontname=\"Noto Sans CJK JP\", fontsize=18];"
  , "  edge  [fontname=\"Noto Sans CJK JP\", fontsize=12,"
  , "         color=\"black\", fontcolor=\"black\","
  , "         penwidth=1.2, arrowsize=0.8];"
  , ""
  , "  // nodes"
  ]
  ++ map renderNode usedProps
  ++ [ "" ]
  ++ rankGroupLines usedProps
  ++
  [ ""
  , "  // edges"
  ]
  ++ map renderEdge es
  ++
  [ "}" ]
  where
    usedProps = nub $ concatMap (\e -> [edgeFrom e, edgeTo e]) es

-- | 同ランクのノードを同じ行に揃える { rank=same; ... } ブロックを生成する。
-- ノードは propColumn の昇順で並べ、左右配置を安定させる。
rankGroupLines :: [Prop] -> [String]
rankGroupLines props =
  let ranks   = sort $ nub [ propRank p | p <- props ]
      inRank r = sortBy (comparing propColumn) [ p | p <- props, propRank p == r ]
  in [ "  { rank=same; " ++ intercalate "; " (map propId (inRank r)) ++ " }"
     | r <- ranks, not (null (inRank r)) ]

renderNode :: Prop -> String
renderNode p =
  "  " ++ propId p ++ " [label=\"" ++ dotPropLabel p ++ "\"];"

renderEdge :: Edge -> String
renderEdge e =
  "  " ++ propId (edgeFrom e) ++ " -> " ++ propId (edgeTo e)
  ++ " [" ++ intercalate ", " attrs ++ "];"
  where
    ctx = contextLabel (edgeCtx e)
    -- ランクが逆行する辺はレイアウト制約から外す
    backward     = propRank (edgeFrom e) > propRank (edgeTo e)
    noConstraint = ["constraint=false" | backward]
    coreAttrs = case edgeKind e of
      Proved    -> ["label=\"" ++ ctx ++ "\""]
      Open      -> ["label=\"? " ++ ctx ++ "\"", "style=dotted"
                   , "color=\"#aa7700\"", "fontcolor=\"#aa7700\""]
      Separated -> ["label=\"x " ++ ctx ++ "\"", "style=dotted"
                   , "color=\"#b00000\"", "fontcolor=\"#b00000\""]
    attrs = noConstraint ++ coreAttrs

propId :: Prop -> String
propId PG2          = "G2"
propId PWFG2        = "WFG2"
propId PFG2         = "FG2"
propId PHasDiamFP   = "DFP"
propId PHasBoxFP    = "BFP"
propId PLoeb        = "Loeb"
propId PFLoeb       = "FLoeb"
propId PConsistency = "Con"

-- | 縦ランク。0 が最上位（最強）。同じランクの命題は同じ行に配置する。
propRank :: Prop -> Int
propRank PHasDiamFP   = 0
propRank PHasBoxFP    = 0
propRank PFG2         = 0
propRank PFLoeb       = 0
propRank PWFG2        = 1
propRank PLoeb        = 1
propRank PG2          = 2
propRank PConsistency = 2

-- | 横列（column）。小さい値が左。同ランク内での左右順序に使う。
-- 偶数列: ☒ 側。奇数/右列: □ 側。
propColumn :: Prop -> Int
propColumn PHasDiamFP   = 0
propColumn PHasBoxFP    = 3
propColumn PFG2         = 1
propColumn PFLoeb       = 2
propColumn PWFG2        = 1
propColumn PLoeb        = 2
propColumn PG2          = 1
propColumn PConsistency = 2

-- | Proved 辺のみ抽出する。正の含意だけを表示したいときに使う。
filterProved :: [Edge] -> [Edge]
filterProved = filter ((== Proved) . edgeKind)

-- ============================================================================
-- TikZ / LaTeX 出力
-- ============================================================================

-- | 命題を LaTeX 数式として表示するための文字列。
tikzPropLabel :: Prop -> String
tikzPropLabel PG2          = "$G_2$"
tikzPropLabel PWFG2        = "$\\mathrm{WFG}_2$"
tikzPropLabel PFG2         = "$\\mathrm{FG}_2$"
tikzPropLabel PHasDiamFP   = "$\\exists\\boxtimes\\text{-FP}$"
tikzPropLabel PHasBoxFP    = "$\\exists\\Box\\text{-FP}$"
tikzPropLabel PLoeb        = "$\\mathrm{Loeb}$"
tikzPropLabel PFLoeb       = "$\\mathrm{FLoeb}$"
tikzPropLabel PConsistency = "$\\mathsf{Con}$"

-- | 文脈を LaTeX 数式として表示するための文字列。
tikzContextLabel :: Context -> String
tikzContextLabel COverPreAPS        = "$\\mathsf{PreAPS}$"
tikzContextLabel COverAPS           = "$\\mathsf{APS}$"
tikzContextLabel COverFixedPointAPS = "$\\mathsf{APS}+\\exists\\boxtimes\\text{-FP}$"
tikzContextLabel COverLoebAPS       = "$\\mathsf{LoebAPS}$"
tikzContextLabel COverImpAPS        = "$\\mathsf{ImpAPS}$"
tikzContextLabel COverFin           = "$\\mathsf{fin}$"
tikzContextLabel (CCustom s)        = "$" ++ tikzifyAxioms s ++ "$"

-- | @A1@, @A2@ などの公理名を添字付きに変換: @A1+A2@ → @A_1+A_2@。
tikzifyAxioms :: String -> String
tikzifyAxioms []                = []
tikzifyAxioms ('A':c:rest) | c `elem` ("0123456789" :: String) =
  'A' : '_' : c : tikzifyAxioms rest
tikzifyAxioms (c:rest) = c : tikzifyAxioms rest

-- | 動物園を LaTeX (TikZ) 形式に変換する。
--
-- 出力は @standalone@ クラスの完全な .tex ファイル。@pdflatex@（または
-- @lualatex@／@xelatex@）でコンパイルできる。命題はノードとして縦一列に配置し、
-- 含意は太線・反例は @\\times@ 入りの点線・未解決は @?@ 入りの点線で描画する。
renderTikZ :: [Edge] -> String
renderTikZ es = unlines $
  [ "% Auto-generated by g2-zoo"
  , "% Compile: pdflatex (or lualatex / xelatex) this-file.tex"
  , "\\documentclass[border=15pt]{standalone}"
  , "\\usepackage[utf8]{inputenc}"
  , "\\usepackage[T1]{fontenc}"
  , "\\usepackage{lmodern}"
  , "\\usepackage{amssymb}"
  , "\\usepackage{tikz}"
  , "\\usetikzlibrary{positioning, arrows.meta, decorations.markings, calc}"
  , "\\begin{document}"
  , "\\begin{tikzpicture}["
  , "  every node/.style={font=\\large, inner sep=2pt},"
  , "  proved/.style={->, thick, >={Stealth[length=2.5mm]}},"
  , "  separated/.style={->, dotted, thick, >={Stealth[length=2.5mm]},"
  , "    postaction={decorate, decoration={markings,"
  , "      mark=at position 0.5 with {\\node[fill=white, inner sep=1pt]{$\\times$};}}}},"
  , "  open/.style={->, dotted, thick, >={Stealth[length=2.5mm]},"
  , "    postaction={decorate, decoration={markings,"
  , "      mark=at position 0.5 with {\\node[fill=white, inner sep=1pt]{$?$};}}}}"
  , "]"
  , "% nodes"
  ]
  ++ map renderTikZNode usedProps
  ++
  [ "% edges"
  ]
  ++ map renderTikZEdge es
  ++
  [ "\\end{tikzpicture}"
  , "\\end{document}"
  ]
  where
    usedProps = nub $ concatMap (\e -> [edgeFrom e, edgeTo e]) es

-- | propRank / propColumn に基づく 2D 格子座標にノードを配置する。
-- x 軸: propColumn × 3.5 cm  (列間隔)
-- y 軸: propRank × (−2.5) cm (行間隔、下に行くほど弱い)
renderTikZNode :: Prop -> String
renderTikZNode p =
  "\\node (" ++ propId p ++ ") at (" ++ x ++ "," ++ y ++ ") {"
  ++ tikzPropLabel p ++ "};"
  where
    x = show (fromIntegral (propColumn p) * (3.5 :: Double))
    y = show (fromIntegral (propRank   p) * (-2.5 :: Double))

-- | 辺を描画する。ランク・列の位置から bend 方向を決める。
renderTikZEdge :: Edge -> String
renderTikZEdge e =
  "\\draw[" ++ style ++ "] (" ++ propId (edgeFrom e) ++ ") "
  ++ "to[" ++ bend ++ "] node[midway, sloped, above, fill=white, inner sep=1pt] {"
  ++ tikzContextLabel (edgeCtx e) ++ "} (" ++ propId (edgeTo e) ++ ");"
  where
    fromRank = propRank   (edgeFrom e)
    toRank   = propRank   (edgeTo   e)
    fromCol  = propColumn (edgeFrom e)
    toCol    = propColumn (edgeTo   e)
    -- 縦方向: 下向き(fromRank < toRank)は右曲がり, 上向きは左曲がり
    -- 横方向: 右向き(fromCol < toCol)は右曲がり, 左向きは左曲がり
    bend | fromRank < toRank  = "bend right=20"
         | fromRank > toRank  = "bend left=20"
         | fromCol  < toCol   = "bend right=15"
         | otherwise          = "bend left=15"
    style = case edgeKind e of
      Proved    -> "proved"
      Separated -> "separated"
      Open      -> "open"

-- ============================================================================

-- | 出典・補足を Markdown 文字列として書き出す。
-- 画像から外した注釈はここに集約する。
renderNotes :: [Edge] -> String
renderNotes es = unlines $
  [ "# G2 Zoo の辺の出典・注釈"
  , ""
  , "本ファイルは `g2-zoo` が動物園を出力する際に同時に生成する。"
  , "画像に載せない出典・補足を辺ごとに列挙する。"
  , ""
  , "| 種別 | from | 文脈 | to | 注釈 |"
  , "|------|------|------|----|------|"
  ]
  ++ map row es
  where
    row e = "| " ++ kind e ++ " | " ++ propLabel (edgeFrom e)
         ++ " | " ++ contextLabel (edgeCtx e)
         ++ " | " ++ propLabel (edgeTo e)
         ++ " | " ++ (if null (edgeNote e) then "—" else edgeNote e)
         ++ " |"
    kind e = case edgeKind e of
      Proved    -> "成立"
      Separated -> "反例あり"
      Open      -> "未解決"
